config/routes.rb
BucketList::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}

  root :to => "home#index"

  resources :lists, :only => [:show] do
    resources :goals, :except => [:new, :destroy, :edit] 
  end

  resources :appropriations do
    resources :notes
  end

  resources :goals, :only => [:show] do
      get 'clone', :on => :member
  end

end

app/models/appropriation.rb
class Appropriation < ActiveRecord::Base
  belongs_to :list
  belongs_to :goal
  has_many :notes

  def editable_by?(user)
    list == user.list
  end
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  has_many :appropriations
  has_many :lists, :through => :appropriations

  def complete?
    status == "complete"
  end

  def forfeited?
    status == "forfeited"
  end

  def incomplete?
    !complete? || !forfeited?
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :appropriations
  has_many :goals, :through => :appropriations

  def editable_by?(user)
    self.user == user
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :appropriation
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_one :list
  after_create :create_list

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token['extra']['user_hash']
    info = access_token['user_info']
    if user = User.find_by_email(data["email"])
      user
    else # Create a user with a stub password. 
      User.create(:email => data["email"], :password => Devise.friendly_token[0,20]) do |u|
        u.name = info["name"]
        #u.username = info["nickname"] 
        #u.avatar = info['image']
        u.uid =  access_token['uid']
        u.token = access_token['credentials']['token']
      end
    end
  end
end


# == Schema Information
#
# Table name: users
#
#  id                     :integer         not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(128)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer         default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  token                  :string(255)
#  uid                    :string(255)
#  name                   :string(255)
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  respond_to :html, :js
  before_filter :authenticate_user!

  def index
  end

  def create
    list = List.find params[:list_id]
    @goal = list.goals.create params[:goal]
    respond_with @goal
  end

  def show
    @goal = if params[:list_id].present?
              @appropriation = Appropriation.find_by_list_id_and_goal_id(params[:list_id], params[:id]) 
              return redirect_to(goal_path(params[:id])) unless @appropriation
              @appropriation.goal
            else
              @appropriation = nil
              Goal.find params[:id]
            end
    respond_with @goal
  end

  def update
  end
  
  def clone
    @goal = Goal.find params[:id]
    current_user.list.goals << @goal
    respond_with @goal
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to list_path(current_user.list) if user_signed_in?
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authenticate_user!
  def show
    @list = List.find params[:id]
    @goal = Goal.new
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  respond_to :js
  def create
    @appropriation = Appropriation.find params[:appropriation_id]
    @note = @appropriation.notes.create params[:note]
    respond_with @note
  end

  def destroy
    @appropriation = Appropriation.find params[:appropriation_id]
    @note = @appropriation.notes.find params[:id]
    @note.destroy
    respond_with @note
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/goals/_note.html.erb
<li id="note_<%=note.id%>"><%= note.content %>
<% if @appropriation.editable_by?(current_user) %>
  <%= link_to "Remove", appropriation_note_path(@appropriation, note), :method => "delete", :confirm => "Are you sure?", :remote => true %>
<%end%>
</li>

app/views/goals/clone.js.erb
alert("ya lo copiaste");

app/views/goals/create.html.erb
<h1>Goals#create</h1>
<p>Find me in app/views/goals/create.html.erb</p>

app/views/goals/create.js.erb
$("#goals").append($("<li></li>").html('<%=raw link_to(@goal.title, goal_path(@goal))%>'));

app/views/goals/index.html.erb
<h1>Goals#index</h1>
<p>Find me in app/views/goals/index.html.erb</p>

app/views/goals/show.html.erb
<h2><%= @goal.title %></h2>
<% if user_signed_in? %>
  <% unless current_user.list.goals.include?(@goal) %>
    <%= link_to "Add to my list", clone_goal_path(@goal), :remote => true %>
  <%end%>
<%end%>
<% if @appropriation %>
  <ul id="notes">
    <%= render :partial => 'note', :collection => @appropriation.notes %>
  </ul>
  <% if @appropriation.editable_by?(current_user)%>
    <%= form_for([@appropriation, Note.new], :remote => true) do |f| %>
      <%= f.text_field :content, {:placeholder => "Add note"} %>
      <%= f.submit %>
    <% end %>
  <%end%>
<%end%>

app/views/goals/update.html.erb
<h1>Goals#update</h1>
<p>Find me in app/views/goals/update.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<% if user_signed_in? %>
  Hi there, <%= current_user.name  %>
<%else%>
  <%= link_to "sign in", new_user_session_path %>
<%end%>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BucketList</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/lists/show.html.erb
<% if @list.editable_by?(current_user) %>
  <%= form_for([@list, @goal], :remote => true) do |f| %>
    <%= f.text_field :title, {:placeholder => "Add a goal"} %>
    <%= f.submit %>
  <% end %>
<% end %>
<ul id="goals">
  <% @list.goals.each do |goal| %>
    <li><%= link_to goal.title, goal_path(goal) %></li>
  <%end%>
</ul>

app/views/notes/create.html.erb
<h1>Notes#create</h1>
<p>Find me in app/views/notes/create.html.erb</p>

app/views/notes/create.js.erb
$("#notes").append('<%= raw render(:partial => 'goals/note', :locals => {:note => @note} ).gsub(/\s+/, ' ') %>');

app/views/notes/destroy.html.erb
<h1>Notes#destroy</h1>
<p>Find me in app/views/notes/destroy.html.erb</p>

app/views/notes/destroy.js.erb
$("#note_<%=@note.id%>").remove();